name: Withinity
version: '${project.version}'
main: me.vase.withinity.Withinity
api-version: 1.19
authors: [vase]
description: Withinity plugin does something

commands:
  god:
    description: Become invincible
    usage: /<command>
    permission: withinity.godCommand

  test:
    description: test tests test
    usage: /<command>
    permission: withinity.testCommand

  setlevel:
    description: Set your level
    usage: /<command> <player> <level>
    permission: withinity.setLevel
  admin:
    description: Administrator Panel
    usage: /<command>
    permission: withinity.admin.panelCommand