name: Withinity
version: '${project.version}'
main: me.vase.withinity.Withinity
api-version: 1.19
authors: [vase]
description: Withinity plugin does something

commands:
  god:
    description: Become invincible
    usage: /<command>
    permission: withinity.admin.godCommand

  test:
    description: test tests test
    usage: /<command>
    permission: withinity.testCommand

  setlevel:
    description: Set your level
    usage: /<command> <player> <level>
    permission: withinity.setLevelCommand

  admin:
    description: Administrator Panel
    usage: /<command>
    permission: withinity.admin.panelCommand

  setwalkingspeed:
    description: Set your walking speed
    usage: /<command> <speed>
    permission: withinity.admin.setWalkingspeedCommand

  walkingspeedmenu:
    description: Opens a menu to set your walking speed
    usage: /<command>
    permission: withinity.admin.setWalkingspeedMenuCommand

  fly:
    description: Enables or disables fly
    usage: /<command>
    permission: withinity.admin.FlightCommand